import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar"
import { Toaster } from "react-hot-toast"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
              <div className="fixed top-0 left-0 w-full z-50">
                  <Navbar />
              </div>

              {/* Push content below navbar */}
              <div className="pt-16">
                  {children}
                  <Toaster
                      position="top-right"
                      animate="toast-progress 5s linear forwards"
                      containerStyle={{
                          top: 70,
                          right: 20,
                      }}
                      toastOptions={{
                          style: {
                              background: "#fff",
                              color: "#043042",
                              border: "1px solid #f97316",
                              borderRadius: "12px",
                              padding: "12px 16px",
                          },
                          success: {
                              iconTheme: {
                                  primary: "#f97316",
                                  secondary: "#fff",
                              },
                          },
                          error: {
                              iconTheme: {
                                  primary: "#ef4444",
                                  secondary: "#fff",
                              },
                          },
                      }}
                  />
              </div>
      </body>
    </html>
  );
}
